name: Send Push Payload to Middleware 
on:
  push: 
    branches:
      - main
      - master
    paths:
      - '**api/**.yaml'

jobs:
  send_payload:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Send payload
      uses: distributhor/workflow-webhook@v2.0.3
      env:
        webhook_type: 'json-extended'
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        
        
